spring:
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/ourtodo?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    #    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ajouwithme@gmail.com
    password: ENC(RRlBDoldIbjSY9+VlM6yvO5vOYsmYmLWSXEeqCity/c=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        web:
          filter: debug

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

jwt:
  secret: ENC(wXcIGSwzpWy0u/2CkJ7F7LQxKA4YPD42GI7kidEdzzQ9+wGnGPdQ4JzKjzewuICM8fFkAVk/ybEhN0RGSVxqxjcFWJfYtA8nSacTcbmaKkU=)

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ENC(NazvhBuFCGW8ylrO34P8cF96IvuGWvVZ)
    url: ENC(JXorvZHxqfox+2d7g9vQaLhoiS6I7JSOlqNDLCzlpQbfjHKPmKd+KUQOQqlAjQ0wcABMGjXX+YiZ3Vu5w9VrVjBozke67kFyc61UnhCd9zH2EEevOVGp/iuyEJZKcoK+LhKw3AEmKWqSZLeI+7bZqQ1qTap1UeJa29Ka6sd/Z9OKXtpGuTftgFsnvLFLJg+g)
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
---

spring:
  config:
    activate:
      on-profile: test

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:../test
